# -*- coding: utf-8 -*-
"""MATH314.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vglrWa4Emauq2J2PsQlb2J36Rrz9PQyD
"""
###################################################

# function for multiplying two binary digtis 
def mult_Binary(num1, num2):
  # convert the input number to int 
  num1_int = int(num1, 2)  
  num2_int = int(num2, 2)
  # multiply the two numbers 
  num_result = num1_int * num2_int
  # convert the int result number to binary by using the bin built in function 
  result_bin = bin(num_result)[2:] # we didi the slicing because the built in function bin adds 0 by default and the slicing will remove it 
  return result_bin

######################################################

# finction for adding two binary numbers 
def add_binary(a,b):
    max_len = max(len(a), len(b))
    a = a.zfill(max_len)
    b = b.zfill(max_len)

    # Initialize the result
    result = ''
    # Initialize the carry
    carry = 0
    # Traverse the string
    for i in range(max_len - 1, -1, -1):
        r = carry
        r += 1 if a[i] == '1' else 0
        r += 1 if b[i] == '1' else 0
        result = ('1' if r % 2 == 1 else '0') + result
        # Compute the carry.
        carry = 0 if r < 2 else 1
    if carry != 0:
        result = '1' + result
    return result.zfill(max_len)

###########################################################

# function for .....










############################################################

# function for ....








############################################################

#main program
print("welcome to MATH314 project! chose what operation you want to do(enter number):")
print("1-binary addtion\n2-binary multiplicatin")
o = input()

if o == "1":
    print("enter first binary number:")
    a = input()
    print("enter second binary number:")
    b = input()
    print("the result is: \n",add_binary(a,b))
elif o == "2":
    print("enter first binary number:")
    a = input()
    print("enter second binary number:")
    b = input()
    print("the result is: \n",mult_Binary(a,b))
